modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustDoom/OhSnap/issues"
license = "MIT"

[[mods]]
modId = "ohsnap"
version = "${version}"
displayName = "Oh Snap"
authors = "JustDoom"
description = '''
Finally, I can now tell when the lead breaks...
'''
logoFile = "logo-forge.png"

[[dependencies.axifier]]
modId = "neoforge"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.axifier]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ohsnap-common.mixins.json"